### ISSUE TITLE
the example in the README would not work

### ISSUE THREAD

**Issue by maxlath** [mafintosh/add-to-systemd#3]
unless there are differences in systemd versions, the example in the README would get the following error:
```
[/lib/systemd/system/my-new-service.service:5] Executable path is not absolute, ignoring: node server.js --port 8080
```

You need to do something like:
```sh
add-to-systemd my-new-service "$(which node) server.js --port 8080"
```

my env:
```
Ubuntu 16.04
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```

**Comment by targos** [comment]
I think you also need to set the `cwd` if the option was not passed.

**Comment by mafintosh** [comment]
`--cwd` defaults to . in the latest version and added the which command to the README. thanks!
