### ISSUE TITLE
Use /etc/systemd/system/ instead of /usr/lib/systemd/system

### ISSUE THREAD

**Issue by bcomnes** [mafintosh/add-to-systemd#6]
From https://wiki.archlinux.org/index.php/systemd

```
/usr/lib/systemd/system/: units provided by installed packages
/etc/systemd/system/: units installed by the system administrator
```

**Comment by mafintosh** [comment]
2.0.0

**Comment by mafintosh** [comment]
2.0.0

**Comment by bcomnes** [comment]
Now this is perfect!

**Comment by A-AFTAHI** [comment]
my question is if i modify a file in /etc/systemd/system , does is it override the /usr/lib/systemd/system? and which file is used when starting a service unit?

**Comment by bcomnes** [comment]
It should, systemd has fairly complex override rules.
